default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_functions_task_app_development

test:
  <<: *default
  database: rails_functions_task_app_test

production:
  <<: *default
  database: rails_functions_task_app_production
  username: rails_functions_task_app
  password: <%= ENV['rails_functions_task_app_DATABASE_PASSWORD'] %>
